import type { Coordinate } from '@/types/api'
import { haversineNm } from './geo'

export interface NamedLocation {
  id: string
  name: string
  country: string
  region: string
  unLocode?: string
  kind: 'port' | 'harbour' | 'anchorage' | 'strait' | 'waypoint'
  coordinate: Coordinate
}

export const NAMED_LOCATIONS: NamedLocation[] = [
  // ==========================================
  // INDIA & SOUTH ASIA (Arabian Sea & Bay of Bengal)
  // ==========================================
  {
    id: 'in-bom-01',
    name: 'Mumbai Port (Seaward Approach)',
    country: 'India',
    region: 'Arabian Sea / West Coast India',
    unLocode: 'INBOM',
    kind: 'port',
    coordinate: { latitude: 18.85, longitude: 72.45 },
  },
  {
    id: 'in-jnp-01',
    name: 'Jawaharlal Nehru Port (JNPT Fairway)',
    country: 'India',
    region: 'Arabian Sea / West Coast India',
    unLocode: 'INJNP',
    kind: 'port',
    coordinate: { latitude: 18.78, longitude: 72.55 },
  },
  {
    id: 'in-bom-anc',
    name: 'Mumbai Outer Deepwater Anchorage',
    country: 'India',
    region: 'Arabian Sea',
    unLocode: 'INBOM',
    kind: 'anchorage',
    coordinate: { latitude: 18.82, longitude: 72.68 },
  },
  {
    id: 'in-ali-01',
    name: 'Alibag Offshore Coastal Waypoint',
    country: 'India',
    region: 'Arabian Sea',
    kind: 'waypoint',
    coordinate: { latitude: 18.52, longitude: 72.55 },
  },
  {
    id: 'in-dgh-01',
    name: 'Dighi Port Seaward Fairway',
    country: 'India',
    region: 'Arabian Sea',
    unLocode: 'INDIG',
    kind: 'port',
    coordinate: { latitude: 18.28, longitude: 72.92 },
  },
  {
    id: 'in-jgd-01',
    name: 'Jaigad Port Deepwater Approach',
    country: 'India',
    region: 'Arabian Sea',
    unLocode: 'INJAI',
    kind: 'port',
    coordinate: { latitude: 17.32, longitude: 73.12 },
  },
  {
    id: 'in-mrm-01',
    name: 'Mormugao Port (Goa Fairway)',
    country: 'India',
    region: 'Arabian Sea / West Coast India',
    unLocode: 'INMRM',
    kind: 'port',
    coordinate: { latitude: 15.42, longitude: 73.75 },
  },
  {
    id: 'in-mnd-01',
    name: 'Mundra Port Fairway (Adani Terminal)',
    country: 'India',
    region: 'Gulf of Kutch / Gujarat',
    unLocode: 'INMUN',
    kind: 'port',
    coordinate: { latitude: 22.72, longitude: 69.70 },
  },
  {
    id: 'in-knd-01',
    name: 'Kandla (Deendayal Port) Fairway',
    country: 'India',
    region: 'Gulf of Kutch / Gujarat',
    unLocode: 'INIXY',
    kind: 'port',
    coordinate: { latitude: 22.95, longitude: 70.15 },
  },
  {
    id: 'in-pip-01',
    name: 'Pipavav Port Seaward Approach (APM Terminals)',
    country: 'India',
    region: 'Gulf of Khambhat / Gujarat',
    unLocode: 'INPAV',
    kind: 'port',
    coordinate: { latitude: 20.90, longitude: 71.52 },
  },
  {
    id: 'in-hzr-01',
    name: 'Hazira Port Fairway (Surat)',
    country: 'India',
    region: 'Gulf of Khambhat',
    unLocode: 'INHZA',
    kind: 'port',
    coordinate: { latitude: 21.08, longitude: 72.62 },
  },
  {
    id: 'in-nml-01',
    name: 'New Mangalore Port Approach',
    country: 'India',
    region: 'Arabian Sea / Karnataka',
    unLocode: 'INNML',
    kind: 'port',
    coordinate: { latitude: 12.92, longitude: 74.78 },
  },
  {
    id: 'in-cok-01',
    name: 'Kochi (Cochin) Port Seaward Pilot Buoy',
    country: 'India',
    region: 'Laccadive Sea / Kerala',
    unLocode: 'INCOK',
    kind: 'port',
    coordinate: { latitude: 9.96, longitude: 76.22 },
  },
  {
    id: 'in-tut-01',
    name: 'V.O. Chidambaranar Port (Tuticorin)',
    country: 'India',
    region: 'Gulf of Mannar / Tamil Nadu',
    unLocode: 'INTCR',
    kind: 'port',
    coordinate: { latitude: 8.75, longitude: 78.18 },
  },
  {
    id: 'in-maa-01',
    name: 'Chennai Port Pilot Boarding Station',
    country: 'India',
    region: 'Bay of Bengal / Tamil Nadu',
    unLocode: 'INMAA',
    kind: 'port',
    coordinate: { latitude: 13.10, longitude: 80.35 },
  },
  {
    id: 'in-kpr-01',
    name: 'Kamarajar Port (Ennore Fairway)',
    country: 'India',
    region: 'Bay of Bengal',
    unLocode: 'INENR',
    kind: 'port',
    coordinate: { latitude: 13.26, longitude: 80.36 },
  },
  {
    id: 'in-ktd-01',
    name: 'Kattupalli Port Approach',
    country: 'India',
    region: 'Bay of Bengal',
    unLocode: 'INKAT',
    kind: 'port',
    coordinate: { latitude: 13.31, longitude: 80.37 },
  },
  {
    id: 'in-kkn-01',
    name: 'Kakinada Deepwater Port Fairway',
    country: 'India',
    region: 'Bay of Bengal',
    unLocode: 'INKAK',
    kind: 'port',
    coordinate: { latitude: 16.98, longitude: 82.28 },
  },
  {
    id: 'in-vtz-01',
    name: 'Visakhapatnam Outer Harbour Fairway',
    country: 'India',
    region: 'Bay of Bengal / Andhra Pradesh',
    unLocode: 'INVTZ',
    kind: 'port',
    coordinate: { latitude: 17.68, longitude: 83.33 },
  },
  {
    id: 'in-pdp-01',
    name: 'Paradip Port Fairway Channel',
    country: 'India',
    region: 'Bay of Bengal / Odisha',
    unLocode: 'INPRT',
    kind: 'port',
    coordinate: { latitude: 20.25, longitude: 86.70 },
  },
  {
    id: 'in-dhm-01',
    name: 'Dhamra Port Approach Channel',
    country: 'India',
    region: 'Bay of Bengal / Odisha',
    unLocode: 'INDHM',
    kind: 'port',
    coordinate: { latitude: 20.80, longitude: 87.05 },
  },
  {
    id: 'in-hld-01',
    name: 'Haldia Dock Complex (Hooghly River)',
    country: 'India',
    region: 'Bay of Bengal / West Bengal',
    unLocode: 'INHLD',
    kind: 'port',
    coordinate: { latitude: 21.90, longitude: 88.10 },
  },
  {
    id: 'in-ccu-01',
    name: 'Kolkata Sandheads Pilot Boarding',
    country: 'India',
    region: 'Bay of Bengal',
    unLocode: 'INCCU',
    kind: 'anchorage',
    coordinate: { latitude: 21.05, longitude: 88.08 },
  },
  {
    id: 'lk-cmb-01',
    name: 'Colombo Port Outer Fairway',
    country: 'Sri Lanka',
    region: 'Indian Ocean',
    unLocode: 'LKCMB',
    kind: 'port',
    coordinate: { latitude: 6.95, longitude: 79.82 },
  },
  {
    id: 'lk-hbt-01',
    name: 'Hambantota International Port (HIPG)',
    country: 'Sri Lanka',
    region: 'Indian Ocean',
    unLocode: 'LKHBA',
    kind: 'port',
    coordinate: { latitude: 6.11, longitude: 81.12 },
  },
  {
    id: 'pk-khi-01',
    name: 'Karachi Port (Manora Fairway)',
    country: 'Pakistan',
    region: 'Arabian Sea / Sindh',
    unLocode: 'PKKHI',
    kind: 'port',
    coordinate: { latitude: 24.78, longitude: 66.97 },
  },
  {
    id: 'pk-pqm-01',
    name: 'Port Muhammad Bin Qasim Channel',
    country: 'Pakistan',
    region: 'Arabian Sea',
    unLocode: 'PKBQM',
    kind: 'port',
    coordinate: { latitude: 24.75, longitude: 67.35 },
  },
  {
    id: 'pk-gwd-01',
    name: 'Gwadar Deepwater Port Fairway',
    country: 'Pakistan',
    region: 'Arabian Sea / Balochistan',
    unLocode: 'PKGWD',
    kind: 'port',
    coordinate: { latitude: 25.11, longitude: 62.33 },
  },
  {
    id: 'bd-cgp-01',
    name: 'Chittagong (Chattogram) Outer Anchorage',
    country: 'Bangladesh',
    region: 'Bay of Bengal',
    unLocode: 'BDCGP',
    kind: 'port',
    coordinate: { latitude: 22.22, longitude: 91.75 },
  },

  // ==========================================
  // MIDDLE EAST, PERSIAN GULF & RED SEA
  // ==========================================
  {
    id: 'ae-dxb-01',
    name: 'Jebel Ali Port (Dubai Fairway)',
    country: 'United Arab Emirates',
    region: 'Persian Gulf',
    unLocode: 'AEJEA',
    kind: 'port',
    coordinate: { latitude: 25.05, longitude: 55.02 },
  },
  {
    id: 'ae-fjr-01',
    name: 'Fujairah Offshore Bunkering Anchorage',
    country: 'United Arab Emirates',
    region: 'Gulf of Oman',
    unLocode: 'AEFJR',
    kind: 'anchorage',
    coordinate: { latitude: 25.18, longitude: 56.40 },
  },
  {
    id: 'ae-auh-01',
    name: 'Khalifa Port / Abu Dhabi Channel',
    country: 'United Arab Emirates',
    region: 'Persian Gulf',
    unLocode: 'AEKHL',
    kind: 'port',
    coordinate: { latitude: 24.88, longitude: 54.68 },
  },
  {
    id: 'om-sll-01',
    name: 'Salalah Port Deepwater Fairway',
    country: 'Oman',
    region: 'Arabian Sea',
    unLocode: 'OMSLL',
    kind: 'port',
    coordinate: { latitude: 16.93, longitude: 54.02 },
  },
  {
    id: 'om-shr-01',
    name: 'Sohar Port Seaward Fairway',
    country: 'Oman',
    region: 'Gulf of Oman',
    unLocode: 'OMSOH',
    kind: 'port',
    coordinate: { latitude: 24.50, longitude: 56.65 },
  },
  {
    id: 'om-dqm-01',
    name: 'Duqm Port Approach Channel',
    country: 'Oman',
    region: 'Arabian Sea',
    unLocode: 'OMDQM',
    kind: 'port',
    coordinate: { latitude: 19.68, longitude: 57.73 },
  },
  {
    id: 'sa-dmm-01',
    name: 'King Abdulaziz Port (Dammam Fairway)',
    country: 'Saudi Arabia',
    region: 'Persian Gulf',
    unLocode: 'SADMM',
    kind: 'port',
    coordinate: { latitude: 26.50, longitude: 50.25 },
  },
  {
    id: 'sa-jed-01',
    name: 'Jeddah Islamic Port Seaward Channel',
    country: 'Saudi Arabia',
    region: 'Red Sea',
    unLocode: 'SAJED',
    kind: 'port',
    coordinate: { latitude: 21.45, longitude: 39.12 },
  },
  {
    id: 'sa-kap-01',
    name: 'King Abdullah Port (Rabigh)',
    country: 'Saudi Arabia',
    region: 'Red Sea',
    unLocode: 'SAKAP',
    kind: 'port',
    coordinate: { latitude: 22.53, longitude: 39.08 },
  },
  {
    id: 'qa-doh-01',
    name: 'Hamad Port / Doha Fairway Channel',
    country: 'Qatar',
    region: 'Persian Gulf',
    unLocode: 'QAHMD',
    kind: 'port',
    coordinate: { latitude: 25.02, longitude: 51.62 },
  },
  {
    id: 'qa-rlf-01',
    name: 'Ras Laffan LNG Terminal Approach',
    country: 'Qatar',
    region: 'Persian Gulf',
    unLocode: 'QARLF',
    kind: 'port',
    coordinate: { latitude: 25.92, longitude: 51.60 },
  },
  {
    id: 'kw-kwt-01',
    name: 'Shuwaikh / Kuwait Port Fairway',
    country: 'Kuwait',
    region: 'Persian Gulf',
    unLocode: 'KWSWK',
    kind: 'port',
    coordinate: { latitude: 29.38, longitude: 47.95 },
  },
  {
    id: 'bh-bah-01',
    name: 'Khalifa Bin Salman Port (Bahrain)',
    country: 'Bahrain',
    region: 'Persian Gulf',
    unLocode: 'BHKBS',
    kind: 'port',
    coordinate: { latitude: 26.18, longitude: 50.72 },
  },
  {
    id: 'eg-sue-01',
    name: 'Suez Canal (South Entrance / Port Tewfik)',
    country: 'Egypt',
    region: 'Red Sea',
    unLocode: 'EGSUZ',
    kind: 'strait',
    coordinate: { latitude: 29.93, longitude: 32.55 },
  },
  {
    id: 'eg-psd-01',
    name: 'Port Said (Suez Canal North Entrance)',
    country: 'Egypt',
    region: 'Mediterranean Sea',
    unLocode: 'EGPSD',
    kind: 'strait',
    coordinate: { latitude: 31.28, longitude: 32.32 },
  },
  {
    id: 'eg-aly-01',
    name: 'Alexandria / Dekheila Port Fairway',
    country: 'Egypt',
    region: 'Mediterranean Sea',
    unLocode: 'EGALY',
    kind: 'port',
    coordinate: { latitude: 31.18, longitude: 29.85 },
  },
  {
    id: 'dj-jib-01',
    name: 'Doraleh Container Terminal (Djibouti)',
    country: 'Djibouti',
    region: 'Bab-el-Mandeb / Gulf of Aden',
    unLocode: 'DJJIB',
    kind: 'port',
    coordinate: { latitude: 11.60, longitude: 43.12 },
  },

  // ==========================================
  // EAST AFRICA & WESTERN INDIAN OCEAN
  // ==========================================
  {
    id: 'ke-mba-01',
    name: 'Mombasa Port (Kilindini Harbour Approach)',
    country: 'Kenya',
    region: 'East Africa / Indian Ocean',
    unLocode: 'KEMBA',
    kind: 'port',
    coordinate: { latitude: -4.07, longitude: 39.67 },
  },
  {
    id: 'tz-dar-01',
    name: 'Dar es Salaam Port Outer Fairway',
    country: 'Tanzania',
    region: 'East Africa / Indian Ocean',
    unLocode: 'TZDAR',
    kind: 'port',
    coordinate: { latitude: -6.82, longitude: 39.31 },
  },
  {
    id: 'mu-plu-01',
    name: 'Port Louis Harbour Fairway',
    country: 'Mauritius',
    region: 'Western Indian Ocean',
    unLocode: 'MUPLU',
    kind: 'port',
    coordinate: { latitude: -20.15, longitude: 57.48 },
  },
  {
    id: 'sc-pov-01',
    name: 'Port Victoria (Mahé Fairway)',
    country: 'Seychelles',
    region: 'Western Indian Ocean',
    unLocode: 'SCPOV',
    kind: 'port',
    coordinate: { latitude: -4.62, longitude: 55.47 },
  },
  {
    id: 'mg-toa-01',
    name: 'Toamasina (Tamatave) Port Fairway',
    country: 'Madagascar',
    region: 'Western Indian Ocean',
    unLocode: 'MGTMM',
    kind: 'port',
    coordinate: { latitude: -18.15, longitude: 49.43 },
  },
  {
    id: 'mz-mpm-01',
    name: 'Maputo Port Seaward Channel',
    country: 'Mozambique',
    region: 'Southern Africa / Indian Ocean',
    unLocode: 'MZMPM',
    kind: 'port',
    coordinate: { latitude: -25.97, longitude: 32.58 },
  },
  {
    id: 'za-dur-01',
    name: 'Port of Durban Outer Anchorage / Fairway',
    country: 'South Africa',
    region: 'Indian Ocean / South Africa',
    unLocode: 'ZADUR',
    kind: 'port',
    coordinate: { latitude: -29.87, longitude: 31.05 },
  },
  {
    id: 'za-rcb-01',
    name: 'Richards Bay Deepwater Coal Terminal Fairway',
    country: 'South Africa',
    region: 'Indian Ocean / South Africa',
    unLocode: 'ZARCB',
    kind: 'port',
    coordinate: { latitude: -28.80, longitude: 32.09 },
  },

  // ==========================================
  // SOUTHEAST ASIA & EAST ASIA
  // ==========================================
  {
    id: 'sg-sin-01',
    name: 'Singapore Eastern Anchorage / Fairway',
    country: 'Singapore',
    region: 'Strait of Singapore',
    unLocode: 'SGSIN',
    kind: 'port',
    coordinate: { latitude: 1.25, longitude: 103.88 },
  },
  {
    id: 'my-pkg-01',
    name: 'Port Klang Pilot Boarding Station',
    country: 'Malaysia',
    region: 'Strait of Malacca',
    unLocode: 'MYPKG',
    kind: 'port',
    coordinate: { latitude: 2.98, longitude: 101.32 },
  },
  {
    id: 'my-tpp-01',
    name: 'Port of Tanjung Pelepas (PTP)',
    country: 'Malaysia',
    region: 'Strait of Malacca / Johor',
    unLocode: 'MYTPP',
    kind: 'port',
    coordinate: { latitude: 1.35, longitude: 103.55 },
  },
  {
    id: 'id-jkt-01',
    name: 'Tanjung Priok Port (Jakarta Fairway)',
    country: 'Indonesia',
    region: 'Java Sea',
    unLocode: 'IDTPP',
    kind: 'port',
    coordinate: { latitude: -6.10, longitude: 106.88 },
  },
  {
    id: 'th-lch-01',
    name: 'Laem Chabang Port Fairway (Bangkok)',
    country: 'Thailand',
    region: 'Gulf of Thailand',
    unLocode: 'THLCH',
    kind: 'port',
    coordinate: { latitude: 13.08, longitude: 100.88 },
  },
  {
    id: 'vn-sgn-01',
    name: 'Cai Mep / Cat Lai (Ho Chi Minh City)',
    country: 'Vietnam',
    region: 'South China Sea',
    unLocode: 'VNSGN',
    kind: 'port',
    coordinate: { latitude: 10.52, longitude: 107.02 },
  },
  {
    id: 'ph-mnl-01',
    name: 'Manila South Harbour Fairway',
    country: 'Philippines',
    region: 'Manila Bay / South China Sea',
    unLocode: 'PHMNL',
    kind: 'port',
    coordinate: { latitude: 14.58, longitude: 120.95 },
  },
  {
    id: 'hk-hkg-01',
    name: 'Hong Kong Kwai Tsing Container Terminal',
    country: 'Hong Kong',
    region: 'Pearl River Delta',
    unLocode: 'HKHKG',
    kind: 'port',
    coordinate: { latitude: 22.33, longitude: 114.12 },
  },
  {
    id: 'cn-szx-01',
    name: 'Shenzhen (Yantian / Shekou Fairway)',
    country: 'China',
    region: 'South China Sea',
    unLocode: 'CNSZX',
    kind: 'port',
    coordinate: { latitude: 22.56, longitude: 114.28 },
  },
  {
    id: 'cn-can-01',
    name: 'Guangzhou (Nansha Terminal Fairway)',
    country: 'China',
    region: 'Pearl River Delta',
    unLocode: 'CNCAN',
    kind: 'port',
    coordinate: { latitude: 22.75, longitude: 113.67 },
  },
  {
    id: 'cn-nbo-01',
    name: 'Ningbo-Zhoushan Port Approach',
    country: 'China',
    region: 'East China Sea',
    unLocode: 'CNNGB',
    kind: 'port',
    coordinate: { latitude: 29.88, longitude: 121.85 },
  },
  {
    id: 'cn-sha-01',
    name: 'Shanghai (Yangshan Deepwater Terminal)',
    country: 'China',
    region: 'East China Sea',
    unLocode: 'CNSHA',
    kind: 'port',
    coordinate: { latitude: 30.62, longitude: 122.06 },
  },
  {
    id: 'cn-tao-01',
    name: 'Qingdao Port Qianwan Fairway',
    country: 'China',
    region: 'Yellow Sea',
    unLocode: 'CNTAO',
    kind: 'port',
    coordinate: { latitude: 36.02, longitude: 120.22 },
  },
  {
    id: 'cn-tsn-01',
    name: 'Tianjin Port (Bohai Bay Approach)',
    country: 'China',
    region: 'Bohai Sea',
    unLocode: 'CNTSN',
    kind: 'port',
    coordinate: { latitude: 38.98, longitude: 117.78 },
  },
  {
    id: 'tw-khh-01',
    name: 'Kaohsiung Port Outer Anchorage',
    country: 'Taiwan',
    region: 'Taiwan Strait',
    unLocode: 'TWKHH',
    kind: 'port',
    coordinate: { latitude: 22.60, longitude: 120.28 },
  },
  {
    id: 'kr-pus-01',
    name: 'Busan New Port Fairway Channel',
    country: 'South Korea',
    region: 'Korea Strait',
    unLocode: 'KRPUS',
    kind: 'port',
    coordinate: { latitude: 35.08, longitude: 128.82 },
  },
  {
    id: 'jp-tyo-01',
    name: 'Tokyo Bay Pilot Station (Yokohama / Tokyo)',
    country: 'Japan',
    region: 'Tokyo Bay / Pacific Ocean',
    unLocode: 'JPTYO',
    kind: 'port',
    coordinate: { latitude: 35.32, longitude: 139.75 },
  },
  {
    id: 'jp-kbe-01',
    name: 'Kobe / Osaka Port Fairway (Hanshin)',
    country: 'Japan',
    region: 'Osaka Bay',
    unLocode: 'JPOSA',
    kind: 'port',
    coordinate: { latitude: 34.65, longitude: 135.42 },
  },

  // ==========================================
  // EUROPE & MEDITERRANEAN
  // ==========================================
  {
    id: 'nl-rtm-01',
    name: 'Port of Rotterdam (Maas Center Fairway)',
    country: 'Netherlands',
    region: 'North Sea',
    unLocode: 'NLRTM',
    kind: 'port',
    coordinate: { latitude: 51.98, longitude: 3.98 },
  },
  {
    id: 'be-anr-01',
    name: 'Port of Antwerp (Scheldt Approach)',
    country: 'Belgium',
    region: 'North Sea',
    unLocode: 'BEANR',
    kind: 'port',
    coordinate: { latitude: 51.32, longitude: 4.30 },
  },
  {
    id: 'de-ham-01',
    name: 'Port of Hamburg (Elbe River Fairway)',
    country: 'Germany',
    region: 'North Sea',
    unLocode: 'DEHAM',
    kind: 'port',
    coordinate: { latitude: 53.53, longitude: 9.92 },
  },
  {
    id: 'de-brv-01',
    name: 'Bremerhaven Container Terminal (Weser)',
    country: 'Germany',
    region: 'North Sea',
    unLocode: 'DEBRV',
    kind: 'port',
    coordinate: { latitude: 53.58, longitude: 8.55 },
  },
  {
    id: 'se-sto-01',
    name: 'Port of Stockholm (Stockholm Archipelago Fairway)',
    country: 'Sweden',
    region: 'Baltic Sea / Scandinavia',
    unLocode: 'SESTO',
    kind: 'port',
    coordinate: { latitude: 59.33, longitude: 18.10 },
  },
  {
    id: 'se-got-01',
    name: 'Port of Gothenburg (Gota Alv Fairway)',
    country: 'Sweden',
    region: 'Kattegat / Scandinavia',
    unLocode: 'SEGOT',
    kind: 'port',
    coordinate: { latitude: 57.70, longitude: 11.90 },
  },
  {
    id: 'fi-hel-01',
    name: 'Port of Helsinki (Vuosaari Fairway)',
    country: 'Finland',
    region: 'Gulf of Finland / Baltic Sea',
    unLocode: 'FIHEL',
    kind: 'port',
    coordinate: { latitude: 60.15, longitude: 25.18 },
  },
  {
    id: 'fi-tku-01',
    name: 'Port of Turku (Archipelago Sea)',
    country: 'Finland',
    region: 'Baltic Sea / Finland',
    unLocode: 'FITKU',
    kind: 'port',
    coordinate: { latitude: 60.43, longitude: 22.22 },
  },
  {
    id: 'ee-tll-01',
    name: 'Port of Tallinn (Muuga Harbour Fairway)',
    country: 'Estonia',
    region: 'Gulf of Finland / Baltic Sea',
    unLocode: 'EETLL',
    kind: 'port',
    coordinate: { latitude: 59.49, longitude: 24.96 },
  },
  {
    id: 'lv-rix-01',
    name: 'Freeport of Riga (Daugava Mouth Fairway)',
    country: 'Latvia',
    region: 'Gulf of Riga / Baltic Sea',
    unLocode: 'LVRIX',
    kind: 'port',
    coordinate: { latitude: 57.05, longitude: 24.02 },
  },
  {
    id: 'lt-klj-01',
    name: 'Klaipeda State Seaport Fairway',
    country: 'Lithuania',
    region: 'Baltic Sea',
    unLocode: 'LTKLJ',
    kind: 'port',
    coordinate: { latitude: 55.70, longitude: 21.12 },
  },
  {
    id: 'pl-gdn-01',
    name: 'Port of Gdansk (Deepwater Container Terminal DCT)',
    country: 'Poland',
    region: 'Baltic Sea',
    unLocode: 'PLGDN',
    kind: 'port',
    coordinate: { latitude: 54.38, longitude: 18.72 },
  },
  {
    id: 'dk-cph-01',
    name: 'Port of Copenhagen (Oresund Sound Fairway)',
    country: 'Denmark',
    region: 'Oresund / Baltic Entrance',
    unLocode: 'DKCPH',
    kind: 'port',
    coordinate: { latitude: 55.70, longitude: 12.60 },
  },
  {
    id: 'no-osl-01',
    name: 'Port of Oslo (Oslofjord Fairway)',
    country: 'Norway',
    region: 'Oslofjord / Scandinavia',
    unLocode: 'NOOSL',
    kind: 'port',
    coordinate: { latitude: 59.88, longitude: 10.72 },
  },
  {
    id: 'no-bgo-01',
    name: 'Port of Bergen (Byfjorden Fairway)',
    country: 'Norway',
    region: 'North Sea / Norwegian Sea',
    unLocode: 'NOBGO',
    kind: 'port',
    coordinate: { latitude: 60.40, longitude: 5.30 },
  },
  {
    id: 'gb-fxs-01',
    name: 'Port of Felixstowe (Harwich Approach)',
    country: 'United Kingdom',
    region: 'North Sea',
    unLocode: 'GBFXS',
    kind: 'port',
    coordinate: { latitude: 51.95, longitude: 1.30 },
  },
  {
    id: 'gb-sou-01',
    name: 'Southampton / Solent Seaward Fairway',
    country: 'United Kingdom',
    region: 'English Channel',
    unLocode: 'GBSOU',
    kind: 'port',
    coordinate: { latitude: 50.88, longitude: -1.35 },
  },
  {
    id: 'fr-leh-01',
    name: 'Le Havre Port 2000 (Seine Bay)',
    country: 'France',
    region: 'English Channel',
    unLocode: 'FRLEH',
    kind: 'port',
    coordinate: { latitude: 49.48, longitude: 0.12 },
  },
  {
    id: 'fr-mrs-01',
    name: 'Marseille-Fos Port (Gulf of Fos)',
    country: 'France',
    region: 'Mediterranean Sea',
    unLocode: 'FRMRS',
    kind: 'port',
    coordinate: { latitude: 43.40, longitude: 4.88 },
  },
  {
    id: 'es-vlc-01',
    name: 'Port of Valencia Fairway Channel',
    country: 'Spain',
    region: 'Western Mediterranean',
    unLocode: 'ESVLC',
    kind: 'port',
    coordinate: { latitude: 39.44, longitude: -0.32 },
  },
  {
    id: 'es-alg-01',
    name: 'Algeciras Bay / Strait of Gibraltar',
    country: 'Spain',
    region: 'Strait of Gibraltar',
    unLocode: 'ESALG',
    kind: 'port',
    coordinate: { latitude: 36.13, longitude: -5.42 },
  },
  {
    id: 'ma-tng-01',
    name: 'Tanger Med Port Fairway Channel',
    country: 'Morocco',
    region: 'Strait of Gibraltar',
    unLocode: 'MAPTM',
    kind: 'port',
    coordinate: { latitude: 35.89, longitude: -5.50 },
  },
  {
    id: 'it-goa-01',
    name: 'Port of Genoa (Vado Ligure Fairway)',
    country: 'Italy',
    region: 'Ligurian Sea',
    unLocode: 'ITGOA',
    kind: 'port',
    coordinate: { latitude: 44.40, longitude: 8.90 },
  },
  {
    id: 'gr-pir-01',
    name: 'Piraeus Port Fairway (Athens / COSCO)',
    country: 'Greece',
    region: 'Aegean Sea',
    unLocode: 'GRPIR',
    kind: 'port',
    coordinate: { latitude: 37.93, longitude: 23.62 },
  },
  {
    id: 'tr-ist-01',
    name: 'Istanbul (Ambarli / Bosphorus South)',
    country: 'Turkey',
    region: 'Sea of Marmara',
    unLocode: 'TRIST',
    kind: 'port',
    coordinate: { latitude: 40.97, longitude: 28.68 },
  },

  // ==========================================
  // AMERICAS & OCEANIA
  // ==========================================
  {
    id: 'pa-bal-01',
    name: 'Panama Canal (Pacific Entrance / Balboa)',
    country: 'Panama',
    region: 'Gulf of Panama',
    unLocode: 'PABAL',
    kind: 'strait',
    coordinate: { latitude: 8.92, longitude: -79.55 },
  },
  {
    id: 'pa-cst-01',
    name: 'Panama Canal (Atlantic Entrance / Cristobal)',
    country: 'Panama',
    region: 'Caribbean Sea',
    unLocode: 'PACRT',
    kind: 'strait',
    coordinate: { latitude: 9.35, longitude: -79.90 },
  },
  {
    id: 'us-lax-01',
    name: 'Port of Los Angeles / Long Beach Pilot Area',
    country: 'United States',
    region: 'Pacific Ocean / California',
    unLocode: 'USLAX',
    kind: 'port',
    coordinate: { latitude: 33.72, longitude: -118.25 },
  },
  {
    id: 'us-hou-01',
    name: 'Houston Ship Channel (Galveston Fairway)',
    country: 'United States',
    region: 'Gulf of Mexico / Texas',
    unLocode: 'USHOU',
    kind: 'port',
    coordinate: { latitude: 29.35, longitude: -94.75 },
  },
  {
    id: 'us-nyc-01',
    name: 'Port of New York & New Jersey (Ambrose Channel)',
    country: 'United States',
    region: 'Atlantic Ocean / New York',
    unLocode: 'USNYC',
    kind: 'port',
    coordinate: { latitude: 40.50, longitude: -73.95 },
  },
  {
    id: 'br-ssz-01',
    name: 'Port of Santos (Outer Fairway)',
    country: 'Brazil',
    region: 'South Atlantic Ocean',
    unLocode: 'BRSSZ',
    kind: 'port',
    coordinate: { latitude: -24.02, longitude: -46.32 },
  },
  {
    id: 'za-dur-01',
    name: 'Durban Port Entrance Fairway',
    country: 'South Africa',
    region: 'Indian Ocean',
    unLocode: 'ZADUR',
    kind: 'port',
    coordinate: { latitude: -29.87, longitude: 31.05 },
  },
  {
    id: 'za-cpt-01',
    name: 'Cape Town (Table Bay Anchorage)',
    country: 'South Africa',
    region: 'South Atlantic Ocean',
    unLocode: 'ZACPT',
    kind: 'port',
    coordinate: { latitude: -33.90, longitude: 18.45 },
  },
  {
    id: 'au-syd-01',
    name: 'Port Botany (Sydney Harbour Fairway)',
    country: 'Australia',
    region: 'Tasman Sea / New South Wales',
    unLocode: 'AUBOT',
    kind: 'port',
    coordinate: { latitude: -34.00, longitude: 151.22 },
  },
  {
    id: 'au-mel-01',
    name: 'Port of Melbourne (Port Phillip Heads)',
    country: 'Australia',
    region: 'Bass Strait / Victoria',
    unLocode: 'AUMEL',
    kind: 'port',
    coordinate: { latitude: -38.30, longitude: 144.62 },
  },
]

/**
 * Searches worldwide ports & harbours by name, country, region, unLocode, or kind.
 * Also understands common country abbreviations and aliases (UK=United Kingdom, UAE, etc.)
 */
export function searchLocations(query: string): NamedLocation[] {
  if (!query || !query.trim()) {
    // Return top global hub ports by default (most frequently used)
    return NAMED_LOCATIONS.slice(0, 12)
  }
  const clean = query.toLowerCase().trim()

  // Expand common abbreviations/aliases into search terms
  const aliases: Record<string, string[]> = {
    'uk': ['united kingdom', 'great britain', 'england', 'britain'],
    'uae': ['united arab emirates', 'emirates'],
    'usa': ['united states', 'america'],
    'us': ['united states', 'america'],
    'hk': ['hong kong'],
    'sg': ['singapore'],
    'ksa': ['saudi arabia'],
    'gcc': ['gulf', 'persian gulf'],
  }

  const expandedTerms: string[] = [clean]
  if (aliases[clean]) {
    expandedTerms.push(...aliases[clean]!)
  }
  // Also reverse: if query matches an alias value, expand to its key(s)
  Object.entries(aliases).forEach(([abbr, full]) => {
    if (full.some((f) => f.includes(clean))) {
      expandedTerms.push(abbr)
    }
  })

  const matches = NAMED_LOCATIONS.filter((loc) => {
    const haystack = [
      loc.name,
      loc.country,
      loc.region,
      loc.kind,
      loc.unLocode ?? '',
    ]
      .join(' ')
      .toLowerCase()

    return expandedTerms.some((term) => haystack.includes(term))
  })

  // Return matched results; empty array if nothing matches (caller handles the empty state)
  return matches
}

/**
 * Returns the name of the nearest location to a given coordinate.
 */
export function nearestLocationName(coord: Coordinate | null | undefined): string {
  if (!coord) return 'Custom Port Location'
  let closest = NAMED_LOCATIONS[0]!
  let minDist = haversineNm(coord, closest.coordinate)

  for (let i = 1; i < NAMED_LOCATIONS.length; i++) {
    const loc = NAMED_LOCATIONS[i]!
    const dist = haversineNm(coord, loc.coordinate)
    if (dist < minDist) {
      minDist = dist
      closest = loc
    }
  }

  if (minDist < 20.0) {
    return `${closest.name}`
  }

  return `${closest.name} (${minDist.toFixed(1)} NM off)`
}
